# Generated by Django 2.0.5 on 2019-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190821_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebycategory',
            name='is_main_category',
            field=models.BooleanField(verbose_name='Основной раздел'),
        ),
    ]
