# Generated by Django 2.0.5 on 2019-08-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190821_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlebycategory',
            old_name='aticle',
            new_name='article',
        ),
    ]
